### PR TITLE
Translation to pt-br

### PR DESCRIPTION
**Pull request by piantino**
Translated to pt-br, issue: https://github.com/open-eid/qt-common/issues/60.

### CODE REVIEW

**Comment by metsma** [comment]
Please can you squash commits and add Signed of line to commit message
https://github.com/open-eid/org/blob/master/CONTRIBUTING.md

**Comment by piantino** [comment]
@metsma It is not working the link:
http://ltsi.linuxfoundation.org/developers/signed-process
In the page:
https://github.com/open-eid/org/blob/master/CONTRIBUTING.md.
I Dont know how can I do this, please help me.

**Comment by metsma** [comment]
See here updated links https://github.com/open-eid/org/pull/2/files

**Comment by piantino** [comment]
Pull request canceled.
See https://github.com/open-eid/qt-common/pull/72

**Pull request closed without merging**
